//TODO: FINISH ADMIN DASHBOARD AND ADD ROUTER
//TODO: CHECK MOBILE COMPATIBILITY
//TODO: FIX ADMIN DASHBOARD ROUTE
//TODO: CONFIRM ON DELETE FOR TRASH ICON
//TODO: Add require to all appendixes
//TODO: Add pdf submit route back on after testing
//TODO: LOADER
//FIXME: CHECKLIST
//FIXME: PDF LAYOUT
//FIXME: PDF GENERATED AFTER LOADING AND NEW PDF FOR EACH USER